### ISSUE TITLE
Where do I have to put this file?

### ISSUE THREAD

**Issue by nalirossi** [schroef/AnimDessin2#1]
Hi! I'm new to programming, I only learnt a few html things in school, so forgive me for my little understanding...

The thing is that I downloaded everything here, extracted the zip and copied it in Programs>Adobe>Photoshop>Presets>Scripts and it doesn't work. Tried too with Programs>Adobe>Photoshop>Presets>Scripts>AnimDessin2-Scripts but doesn't seem to be working either.
I am running Photoshop CC2020 in Windows.

If you could help me I would appreciate it a lot! :) 

Thank you.

**Comment by rickdelaney** [comment]
I've been using AD2 & AC2 for a number of years. It's wonderful.  I don't see where I can add the new features that show/hide tooltips, etc. I uninstalled, downloaded and reinstalled AD2 & AD2 but there are no new features. Is there something I am missing? I am on a Mac if that means anything.  Please assist.

**Comment by ghost** [comment]
@nalirossi @rickdelaney hi guys
just paste everything in jsx and icon file to the AnimDessin2 script file of photoshop's preset and restart photoshop, it will works.
"C:\Program Files\Adobe\Adobe Photoshop CC 2019\Presets\Scripts\AnimDessin2-Scripts"

**Comment by schroef** [comment]
Im in the process of updating the main readme file. In the meantime, people can look at [this post](https://github.com/sbaril/Photoshop-Animation/issues/15#issuecomment-744687409) for the manual install method

**Comment by schroef** [comment]
Closing this after months of no replies
