### ISSUE TITLE
Feature request: Locate layer/frame in timeline

### ISSUE THREAD

**Issue by pinneh** [schroef/AnimDessin2#3]
By control left-clicking a layer in the canvas, a user selects and scrolls to the layer they clicked on.
I would like to request that either:
- This event also scrolls to the relevant frame.
- Or a button be added that scrolls to the selected frame when a user clicks it.

**Comment by schroef** [comment]
Sorry that is not possible i belive, ive already tried this. There doesnt seem to be any connection between time and layers.

I do however have been working on a better scroll/scrub system, its acts like a global scrubber, kinda like After Effects scrubber, you can check this post i made a while back

Though you still need to select the frame below the player, there is no link between these two. Ive tried so many trick and things i could find. Photoshop and especially timeline is very limited in the documentation, lots seem to be internal code and can not be done by scripting
https://github.com/sbaril/Photoshop-Animation/issues/8#issuecomment-662012007

I do how ever have made a method where layer and time frame to step forward or backwarsd 1 or 2 frames at a time. But i cant use that for my timeframe. Sometimes certain frames can be longer, but that information is not stored or reachable for code

**Comment by schroef** [comment]
PS you can use the hotkeys with first request. If you use ctrl + LMB to select the layer, the frame will be selected in the timeline, if you then press up, the playhead will align to that frame.

Though this trick only works when something is actually on this layer. If the layer is black it will not trigger

**Comment by pinneh** [comment]
Thanks for the swift response. I was afraid it wouldn't be possible, but figured i may as well ask. I looked into it briefly as well, and had no idea where to begin.

**Comment by schroef** [comment]
Well there is one method you can use. if you add frame numbering in each layer. You do neet to manually add these or use some script for this.

That way you can cmd or ctrl click that layer and it will select the proper frame in the timeline. This method of selecting is a default Photoshop function and it transfer over correct to the frame animation timeline
